# Generated by Django 5.1.4 on 2025-01-08 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Id',
            fields=[
                ('name', models.CharField(max_length=25, verbose_name='НАзвание игры')),
                ('number', models.FloatField(max_length=30, primary_key=True, serialize=False, verbose_name='Айди игры')),
            ],
            options={
                'verbose_name': 'Аййдишник',
                'verbose_name_plural': 'Айдишники',
            },
        ),
        migrations.CreateModel(
            name='Steam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25, verbose_name='Логин')),
                ('password', models.CharField(max_length=25, verbose_name='Пароль')),
                ('secret_key', models.CharField(max_length=30, verbose_name='секретный ключ')),
                ('status', models.BooleanField(default=0, verbose_name='Статус аккаунта')),
                ('gamename', models.CharField(max_length=15, verbose_name='Игры на аккаунте')),
                ('gameid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.id')),
            ],
            options={
                'verbose_name': 'Steam',
                'verbose_name_plural': 'Steam',
            },
        ),
    ]
