# Generated by Django 5.1.4 on 2025-01-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25, verbose_name='Логин')),
                ('password', models.CharField(max_length=25, verbose_name='Пароль')),
                ('secret_key', models.CharField(max_length=30, verbose_name='секретный ключ')),
                ('status', models.BooleanField(default=0, verbose_name='Статус аккаунта')),
                ('gamename', models.CharField(max_length=15, verbose_name='Игры на аккаунте')),
            ],
            options={
                'verbose_name': 'Epic',
                'verbose_name_plural': 'Epic',
            },
        ),
    ]
