# Generated by Django 5.1.4 on 2025-02-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_id_options_remove_steam_id_alter_id_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steam',
            name='gameid',
        ),
    ]
