# Generated by Django 5.1.4 on 2025-02-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_id_slug_steam_game_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steam',
            name='gamename',
        ),
        migrations.AlterField(
            model_name='id',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
